FROM node:20-alpine

WORKDIR /app

# Install dependencies based on monorepo structure
COPY package.json ./
COPY apps/web/package.json ./apps/web/
COPY packages/config/package.json ./packages/config/

RUN npm install

# Copy monorepo contents
COPY . .

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"
ENV WATCHPACK_POLLING true

CMD ["npm", "run", "dev", "--workspace=apps/web"]
